### ISSUE TITLE
Invalid module references in generated bindings

### ISSUE THREAD

**Issue by mperham** [macks/ruby-protobuf#1]
```
module Com
  module Largesmall
    module Crawler
      module Model
        module Protobuf
          ::Protobuf::OPTIONS[:"java_package"] = "com.largesmall.crawler.model.protobuf"
          class PagePageInlink < ::Protobuf::Message
            defined_in __FILE__
            required :'com::largesmall::crawler::model::protobuf::PagePageLinkMetadata', :metadata, 1
          end
```

Notice the module is Com::Largesmall::... but the symbol is "com::largesmall::...".  The case is wrong.

**Comment by macks** [comment]
Thanks for your report.
I think this issue was fixed in the commit: 4571ac1d7e9f43c114b9945165d93d30b7c2a605

**Comment by mperham** [comment]
It was not.  I sent a pull request that fixes the problem.

**Comment by macks** [comment]
Please see my test case: 394a8a358f5b6a75e079a9eacf2455409023fb5c

The symbol is still lowercase, but suited message class will be found at run-time.

**Comment by mperham** [comment]
Then why are we seeing these errors?

```
qanat.rb:74: NameError: wrong constant name com
qanat.rb:75: /Users/mike/.rvm/gems/ruby-1.9.1-p378/gems/ruby_protobuf-0.4.0/lib/protobuf/message/field.rb:272:in `const_defined?'
/Users/mike/.rvm/gems/ruby-1.9.1-p378/gems/ruby_protobuf-0.4.0/lib/protobuf/message/field.rb:272:in `block in     typename_to_class'
/Users/mike/.rvm/gems/ruby-1.9.1-p378/gems/ruby_protobuf-0.4.0/lib/protobuf/message/field.rb:271:in `each'
/Users/mike/.rvm/gems/ruby-1.9.1-p378/gems/ruby_protobuf-0.4.0/lib/protobuf/message/field.rb:271:in `inject'
/Users/mike/.rvm/gems/ruby-1.9.1-p378/gems/ruby_protobuf-0.4.0/lib/protobuf/message/field.rb:271:in `typename_to_class'
```

**Comment by mperham** [comment]
We probably have an old version of the code.  I'll test against HEAD.

**Comment by mperham** [comment]
It works on HEAD, thanks.  Your Manifest.txt is out of date, does not include util.rb.

**Comment by macks** [comment]
I've fixed Manifest.txt in 0e7bff90b5f9e50702ed89a0dad72085b44f705b
Thank you.
