### ISSUE TITLE
Can't compile D3 proto files

### ISSUE THREAD

**Issue by pcasaretto** [macks/ruby-protobuf#11]
When I try to compile the proto files from https://github.com/codeweaver/proto/tree/master/definitions I get

```
proto.y:156:in `_reduce_124': undefined method `unshift' for :bnet:Symbol (NoMethodError)
    from proto.y:208:in `scan'
    from racc/parser.rb:152:in `_racc_yyparse_c'
    from racc/parser.rb:152:in `yyparse'
    from proto.y:175:in `parse'
    from /Users/pcasaretto/.rvm/gems/ruby-1.9.2-p290/gems/ruby_protobuf-0.4.11/lib/protobuf/compiler/compiler.rb:23:in `block in create_message'
    from /Users/pcasaretto/.rvm/gems/ruby-1.9.2-p290/gems/ruby_protobuf-0.4.11/lib/protobuf/compiler/compiler.rb:22:in `open'
    from /Users/pcasaretto/.rvm/gems/ruby-1.9.2-p290/gems/ruby_protobuf-0.4.11/lib/protobuf/compiler/compiler.rb:22:in `create_message'
    from /Users/pcasaretto/.rvm/gems/ruby-1.9.2-p290/gems/ruby_protobuf-0.4.11/lib/protobuf/compiler/compiler.rb:13:in `compile'
    from /Users/pcasaretto/.rvm/gems/ruby-1.9.2-p290/gems/ruby_protobuf-0.4.11/lib/protobuf/compiler/compiler.rb:9:in `compile'
    from /Users/pcasaretto/.rvm/gems/ruby-1.9.2-p290/gems/ruby_protobuf-0.4.11/bin/rprotoc:40:in `<top (required)>'
    from /Users/pcasaretto/.rvm/gems/ruby-1.9.2-p290/bin/rprotoc:19:in `load'
    from /Users/pcasaretto/.rvm/gems/ruby-1.9.2-p290/bin/rprotoc:19:in `<main>'
```

protoc compiles these just fine.
It seems the problem is with the .bnet. and .D3. tags . If I remove them I get

```
/Users/pcasaretto/.rvm/gems/ruby-1.9.2-p290/gems/ruby_protobuf-0.4.11/lib/protobuf/message/message.rb:43:in `define_field': Field tag 1 has already been used in Google::Protobuf::FileDescriptorProto. (Protobuf::TagCollisionError)
```

**Comment by pcasaretto** [comment]
It seems the error is connected to this.

Packages and Name Resolution

Type name resolution in the protocol buffer language works like C++: first the innermost scope is searched, then the next-innermost, and so on, with each package considered to be "inner" to its parent package. A leading '.' (for example, .foo.bar.Baz) means to start from the outermost scope instead.
